[[plugins]] # unite all interfaces
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
if = 'has("nvim")'
hook_add = '''
  nmap <Leader>u [denite]
  nnoremap <silent> [denite]b :Denite buffer<CR>
  nnoremap <silent> [denite]l :Denite line<CR>
  nnoremap <silent> [denite]f :Denite file_rec<CR>
  nnoremap <silent> [denite]g :Denite grep<CR>
  nnoremap <silent> [denite]G :DeniteCursorWord grep<CR>
  nnoremap <silent> [denite]; :Denite -resume -immediately -select=+1<CR>
  nnoremap <silent> [denite], :Denite -resume -immediately -select=-1<CR>
'''
hook_source = '''
  call denite#custom#option('default', 'prompt', '>>>')
  call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
  call denite#custom#source('grep', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', ['.git/', 'vendor/', 'node_modules', 'images/', 'img/'])
'''

# [[plugins]] # completion for javascript
# repo = 'othree/yajs.vim'
# on_ft = 'javascript'
# on_i = 1

# [[plugins]]
# repo = 'billyvg/tigris.nvim'
# if = 'has("nvim")'
# on_ft = ['javascript', 'javascript.jsx']
# hook_add = '''
#   let g:tigris#enabled = 1
#   let g:tigris#on_the_fly_enabled = 1
#   let g:tigris#delay = 300
# '''

[[plugins]] # completion for python
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_ft = 'python'
on_i = 1
hook_source = '''
  let g:deoplete#sources#jedi#python_path = g:python3_host_prog
'''

[[plugins]] # completion for go
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = 'go'
on_i = 1

[[plugins]] # formatting for go
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # syntax highlighting, formatting for rust
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:syntastic_rust_checkers = ['cargo']
  let g:rustfmt_command = "~/.cargo/bin/rustfmt"
  let g:rustfmt_autosave = 1
'''

[[plugins]] # completion for rust
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  let g:racer_cmd = "~/.cargo/bin/racer"
  let g:racer_experimental_completer = 1
'''
