[[plugins]] # plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # completion framework
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]] # snippet
repo = 'Shougo/neosnippet.vim'

[[plugins]] # The standard snippets repository for neosnippet.
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # status line
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_symbols = {}
  let g:airline_symbols.maxlinenr = ''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'unique_tail'
'''

[[plugins]]
repo = '~/workspace/neovim/surround.nvim'
hook_add = '''
  nmap <Leader>s [surround]
  nnoremap <silent> [surround]l :SurroundLine
  nnoremap <silent> [surround]w :SurroundWord
  nnoremap <silent> [surround]c :ChSurround
  nnoremap <silent> [surround]r :RmSurround<CR>
'''
