# https://github.com/ianyh/Amethyst/blob/v0.22.0/docs/configuration-files.md

layouts:
  - fullscreen
  - two-pane

# true if the mouse should move position to the center of a window when it becomes focused (default false). Note that this is largely incompatible with focus-follows-mouse.
mouse-follows-focus: false

# true if the windows underneath the mouse should become focused as the mouse moves (default false). Note that this is largely incompatible with mouse-follows-focus
focus-follows-mouse: false

# true if dragging and dropping windows on to each other should swap their positions (default false).
mouse-swaps-windows: true

# true if changing the frame of a window with the mouse should update the layout to accommodate the change (default false). Note that not all layouts will be able to respond to the change.
mouse-resizes-windows: true

# true to insert new windows into the first position and false to insert new windows into the last position (default false).
new-windows-to-main: true

# true to automatically move to a space when throwing a window to it (default true).
follow-space-thrown-windows: true

# The integer percentage of the screen dimension to increment and decrement main pane ratios by (default 5).
window-resize-step: 10

# キーバインドを複雑にしデフォルトのショートカットを封殺する
mod1:
  - command
  - option
  - control
  - shift
mod2:
  - command
  - option
  - control
mod3:
  - option
mod4:
  - option
  - control

cycle-layout:
  mod: mod3
  key: e
shrink-main:
  mod: mod3
  key: ','
expand-main:
  mod: mod3
  key: '.'
focus-ccw:
  mod: mod3
  key: space
focus-main:
  mod: mod3
  key: m
focus-screen-ccw:
  mod: mod3
  key: enter
swap-screen-ccw:
  mod: mod4
  key: enter
swap-main:
  mod: mod4
  key: m
relaunch-amethyst:
  mod: mod4
  key: z
