[[plugins]] # plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # status line
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_symbols = {}
  let g:airline_symbols.maxlinenr = ''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'unique_tail'
'''

[[plugins]] # status line themes
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='everforest'
'''

[[plugins]] # An ecosystem of Vim/Neovim which allows developers to write plugins in Deno.
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'atsuya0/dps-surrounding.vim'
hook_add = '''
  nmap <LocalLeader>s [surrounding]
  nnoremap <silent> [surrounding]l :SurroundLine<space>
  nnoremap <silent> [surrounding]w :SurroundWord<space>
  nnoremap <silent> [surrounding]c :ChSurround<space>
  nnoremap <silent> [surrounding]r :RmSurround<CR>
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
