[[plugins]] # completion for javascript
repo = 'othree/yajs.vim'
on_ft = 'javascript'
on_i = 1

[[plugins]] # completion for python
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_ft = 'python'
on_i = 1
hook_source = '''
  let g:deoplete#sources#jedi#python_path = g:python3_host_prog
'''

[[plugins]] # completion for go
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = 'go'
on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
