# [[plugins]] # completion for javascript
# repo = 'othree/yajs.vim'
# on_ft = 'javascript'
# on_i = 1

[[plugins]]
repo = 'billyvg/tigris.nvim'
if = 'has("nvim")'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
  let g:tigris#enabled = 1
  let g:tigris#on_the_fly_enabled = 1
  let g:tigris#delay = 300
'''

[[plugins]] # completion for python
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_ft = 'python'
on_i = 1
hook_source = '''
  let g:deoplete#sources#jedi#python_path = g:python3_host_prog
'''

[[plugins]] # completion for go
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = 'go'
on_i = 1

[[plugins]] # formatting for go
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # syntax highlighting, formatting for rust
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:syntastic_rust_checkers = ['cargo']
  let g:rustfmt_command = "~/.cargo/bin/rustfmt"
  let g:rustfmt_autosave = 1
'''

[[plugins]] # completion for rust
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  let g:racer_cmd = "~/.cargo/bin/racer"
  let g:racer_experimental_completer = 1
'''
