# https://yazi-rs.github.io/docs/configuration/yazi
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[preview]
image_quality = 90

[opener]
image_viewr = [
	{ run = '/Users/atsuya/dotfiles/bin/images_viewer.sh "$1"', block = true, for = "unix" },
]

[open]
rules = [
	# Folder
	{ name = "*/", use = [ "image_viewr" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Fallback
	{ name = "*", use = [ "open", "reveal" ] },
]
