# https://yazi-rs.github.io/docs/configuration/yazi
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
[mgr]
append_keymap = [
	{ on = "A-d", run = [ "/Users/atsuya/workspace/go/bin/trs", "move" ] }
]

[preview]
image_quality = 90

[opener]
image_viewr = [
	{ run = '/Users/atsuya/dotfiles/bin/images_viewer.sh "$1"', block = false, for = "unix" },
]

[open]
append_rules = [
	{ name = "*/", use = "image_viewr" },
]
